language: php


matrix:
  include:
  - php: 5.6
    before_script: pecl install redis
  - php: 7.0
  - php: hhvm
  global:
  - composer self-update
  - composer --version
  - composer update
  - composer install --dev

allow_failures:
  - php: 7.0
  - php: hhvm

script:
    phpunit -v --configuration phpunit.xml --bootstrap tests/bootstrap.php tests/*
