language: php

before_script:
    - pecl install redis
    - composer self-update
    - composer --version
    - composer update
    - composer install --dev
php:
  - 5.6
  - 7.0
  - hhvm

allow_failures:
  - php: 7.0
  - php: hhvm

script:
    phpunit -v --configuration phpunit.xml --bootstrap tests/bootstrap.php tests/*
